set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
#set_property BITSTREAM.CONFIG.CONFIGFALLBACK ENABLE [current_design]
#set_property BITSTREAM.CONFIG.NEXT_CONFIG_ADDR 0x0100000 [current_design]

#set_property FILE_TYPE {VHDL 2008} [current_design]

######################

# Pines y estandares de niveles logicos

#Clock
set_property PACKAGE_PIN Y18 [get_ports CLK_50]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_50]

#Leds 
set_property PACKAGE_PIN H13 [get_ports LED5]
set_property IOSTANDARD LVCMOS33 [get_ports LED5]
set_property PACKAGE_PIN G15 [get_ports LED6]
set_property IOSTANDARD LVCMOS33 [get_ports LED6]

#Keyboard and mouse
set_property PACKAGE_PIN U1 [get_ports PS2_KEYBOARD_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_KEYBOARD_CLK]
set_property PULLUP true [get_ports PS2_KEYBOARD_CLK]
set_property PACKAGE_PIN T1 [get_ports PS2_KEYBOARD_DAT]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_KEYBOARD_DAT]
set_property PULLUP true [get_ports PS2_KEYBOARD_DAT]
set_property PACKAGE_PIN P4 [get_ports PS2_MOUSE_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_MOUSE_CLK]
set_property PULLUP true [get_ports PS2_MOUSE_CLK]
set_property PACKAGE_PIN N5 [get_ports PS2_MOUSE_DAT]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_MOUSE_DAT]
set_property PULLUP true [get_ports PS2_MOUSE_DAT]

# Video output
set_property PACKAGE_PIN V18 [get_ports VGA_HS]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_HS]
set_property PACKAGE_PIN P19 [get_ports VGA_VS]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_VS]
set_property PACKAGE_PIN W21 [get_ports {VGA_B[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[7]}]
set_property PACKAGE_PIN W19 [get_ports {VGA_B[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[6]}]
set_property PACKAGE_PIN AA20 [get_ports {VGA_B[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[5]}]
set_property PACKAGE_PIN Y21 [get_ports {VGA_B[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[4]}]
set_property PACKAGE_PIN AB21 [get_ports {VGA_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
set_property PACKAGE_PIN T20 [get_ports {VGA_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property PACKAGE_PIN U5 [get_ports {VGA_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN T6 [get_ports {VGA_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]

set_property PACKAGE_PIN W17 [get_ports {VGA_R[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[7]}]
set_property PACKAGE_PIN AA19 [get_ports {VGA_R[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[6]}]
set_property PACKAGE_PIN AB20 [get_ports {VGA_R[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[5]}]
set_property PACKAGE_PIN V20 [get_ports {VGA_R[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[4]}]
set_property PACKAGE_PIN Y19 [get_ports {VGA_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
set_property PACKAGE_PIN P20 [get_ports {VGA_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property PACKAGE_PIN T5 [get_ports {VGA_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN R6 [get_ports {VGA_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]

set_property PACKAGE_PIN W22 [get_ports {VGA_G[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[7]}]
set_property PACKAGE_PIN AA21 [get_ports {VGA_G[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[6]}]
set_property PACKAGE_PIN Y22 [get_ports {VGA_G[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[5]}]
set_property PACKAGE_PIN AB22 [get_ports {VGA_G[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[4]}]
set_property PACKAGE_PIN W20 [get_ports {VGA_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
set_property PACKAGE_PIN V17 [get_ports {VGA_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property PACKAGE_PIN V4 [get_ports {VGA_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN V5 [get_ports {VGA_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]

#Audio Delta.Sigma
set_property PACKAGE_PIN V19 [get_ports PWM_AUDIO_L]
set_property IOSTANDARD LVCMOS33 [get_ports PWM_AUDIO_L]
set_property PACKAGE_PIN U17 [get_ports PWM_AUDIO_R]
set_property IOSTANDARD LVCMOS33 [get_ports PWM_AUDIO_R]

#Audio Ear
#set_property PACKAGE_PIN B1 [get_ports ear_i]
#set_property IOSTANDARD LVCMOS33 [get_ports ear_i]
#set_property PULLUP true [get_ports ear_i]

#Audio I2S
set_property PACKAGE_PIN V9 [get_ports I2S_BCLK]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_BCLK]
set_property PACKAGE_PIN U7 [get_ports I2S_LRCLK]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_LRCLK]
set_property PACKAGE_PIN U6 [get_ports I2S_DATA]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_DATA]

#Joystick
set_property PACKAGE_PIN G1 [get_ports joy_sel]
set_property IOSTANDARD LVCMOS33 [get_ports joy_sel]
set_property PACKAGE_PIN V2 [get_ports joy_clk]
set_property IOSTANDARD LVCMOS33 [get_ports joy_clk]
set_property PACKAGE_PIN U2 [get_ports joy_load_n]
set_property IOSTANDARD LVCMOS33 [get_ports joy_load_n]
set_property PACKAGE_PIN W2 [get_ports joy_data]
set_property IOSTANDARD LVCMOS33 [get_ports joy_data]
set_property PULLUP true [get_ports joy_data]

#SRAM
#set_property PACKAGE_PIN U18 [get_ports {sramA[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramA[0]}]
#set_property PACKAGE_PIN AB18 [get_ports {sramA[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramA[1]}]
#set_property PACKAGE_PIN P15 [get_ports {sramA[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramA[2]}]
#set_property PACKAGE_PIN T18 [get_ports {sramA[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramA[3]}]
#set_property PACKAGE_PIN R17 [get_ports {sramA[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramA[4]}]
#set_property PACKAGE_PIN P14 [get_ports {sramA[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramA[5]}]
#set_property PACKAGE_PIN AB3 [get_ports {sramA[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramA[6]}]
#set_property PACKAGE_PIN Y3 [get_ports {sramA[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramA[7]}]
#set_property PACKAGE_PIN R14 [get_ports {sramA[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramA[8]}]
#set_property PACKAGE_PIN T3 [get_ports {sramA[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramA[9]}]
#set_property PACKAGE_PIN P16 [get_ports {sramA[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramA[10]}]
#set_property PACKAGE_PIN AA3 [get_ports {sramA[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramA[11]}]
#set_property PACKAGE_PIN P17 [get_ports {sramA[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramA[12]}]
#set_property PACKAGE_PIN AB2 [get_ports {sramA[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramA[13]}]
#set_property PACKAGE_PIN AA18 [get_ports {sramA[14]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramA[14]}]
#set_property PACKAGE_PIN Y2 [get_ports {sramA[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramA[15]}]
#set_property PACKAGE_PIN Y1 [get_ports {sramA[16]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramA[16]}]
#set_property PACKAGE_PIN W1 [get_ports {sramA[17]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramA[17]}]
#set_property PACKAGE_PIN V3 [get_ports {sramA[18]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramA[18]}]
#set_property PACKAGE_PIN G2 [get_ports {sramA[19]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramA[19]}]

#set_property PACKAGE_PIN N17 [get_ports {sramDQ[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramDQ[0]}]
#set_property PACKAGE_PIN AA5 [get_ports {sramDQ[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramDQ[1]}]
#set_property PACKAGE_PIN N14 [get_ports {sramDQ[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramDQ[2]}]
#set_property PACKAGE_PIN N13 [get_ports {sramDQ[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramDQ[3]}]
#set_property PACKAGE_PIN R16 [get_ports {sramDQ[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramDQ[4]}]
#set_property PACKAGE_PIN AA1 [get_ports {sramDQ[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramDQ[5]}]
#set_property PACKAGE_PIN AB1 [get_ports {sramDQ[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramDQ[6]}]
#set_property PACKAGE_PIN U3 [get_ports {sramDQ[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramDQ[7]}]

#set_property PACKAGE_PIN N2 [get_ports {sramDQ[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramDQ[8]}]
#set_property PACKAGE_PIN P2 [get_ports {sramDQ[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramDQ[9]}]
#set_property PACKAGE_PIN P1 [get_ports {sramDQ[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramDQ[10]}]s
#set_property PACKAGE_PIN R1 [get_ports {sramDQ[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramDQ[11]}]
#set_property PACKAGE_PIN K6 [get_ports {sramDQ[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramDQ[12]}]
#set_property PACKAGE_PIN L1 [get_ports {sramDQ[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramDQ[13]}]
#set_property PACKAGE_PIN M1 [get_ports {sramDQ[14]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramDQ[14]}]
#set_property PACKAGE_PIN K4 [get_ports {sramDQ[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sramDQ[15]}]

#set_property PACKAGE_PIN N15 [get_ports sramWe]
#set_property IOSTANDARD LVCMOS33 [get_ports sramWe]

#set_property PACKAGE_PIN E1 [get_ports sram_ceoe_n_o]
#set_property IOSTANDARD LVCMOS33 [get_ports sram_ceoe_n_o]

#set_property PACKAGE_PIN U20 [get_ports sram_ub_n_o]
#set_property IOSTANDARD LVCMOS33 [get_ports sram_ub_n_o]

#set_property PACKAGE_PIN N4 [get_ports sram_lb_n_o]
#set_property IOSTANDARD LVCMOS33 [get_ports sram_lb_n_o]

#SD
set_property PACKAGE_PIN M6 [get_ports SD_SCLK_O]
set_property IOSTANDARD LVCMOS33 [get_ports SD_SCLK_O]
set_property PACKAGE_PIN L5 [get_ports SD_CS_N_O]
set_property IOSTANDARD LVCMOS33 [get_ports SD_CS_N_O]
set_property PACKAGE_PIN M5 [get_ports SD_MISO_I]
set_property IOSTANDARD LVCMOS33 [get_ports SD_MISO_I]
set_property PULLUP true [get_ports SD_MISO_I]
set_property PACKAGE_PIN L4 [get_ports SD_MOSI_O]
set_property IOSTANDARD LVCMOS33 [get_ports SD_MOSI_O]

#Flash SPI
#set_property PACKAGE_PIN T4 [get_ports flash_sclk_o]
#set_property IOSTANDARD LVCMOS33 [get_ports flash_sclk_o]
#set_property PACKAGE_PIN T19 [get_ports flash_cs_n_o]
#set_property IOSTANDARD LVCMOS33 [get_ports flash_cs_n_o]
#set_property PACKAGE_PIN R22 [get_ports flash_miso_i]
# DQ1
#set_property IOSTANDARD LVCMOS33 [get_ports flash_miso_i]  
#set_property PULLUP true [get_ports flash_miso_i]
# DQ0
#set_property PACKAGE_PIN P22 [get_ports flash_mosi_o]
#set_property IOSTANDARD LVCMOS33 [get_ports flash_mosi_o]  
#set_property PACKAGE_PIN P21 [get_ports flash_wp_o]
#set_property IOSTANDARD LVCMOS33 [get_ports flash_wp_o]
#set_property PACKAGE_PIN R21 [get_ports flash_hold_o]
#set_property IOSTANDARD LVCMOS33 [get_ports flash_hold_o]

#
# SDRAM signals
#
set_property PACKAGE_PIN G20 [get_ports DRAM_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_CLK]
set_property PACKAGE_PIN H22 [get_ports DRAM_CKE]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_CKE]

set_property PACKAGE_PIN L21 [get_ports DRAM_UDQM]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_UDQM]
set_property PACKAGE_PIN M18 [get_ports DRAM_LDQM]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_LDQM]

set_property PACKAGE_PIN L18 [get_ports DRAM_CAS_N]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_CAS_N]
set_property PACKAGE_PIN K19 [get_ports DRAM_RAS_N]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_RAS_N]
set_property PACKAGE_PIN J17 [get_ports DRAM_WE_N]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_WE_N]
set_property PACKAGE_PIN N22 [get_ports DRAM_CS_N]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_CS_N]

set_property PACKAGE_PIN H20 [get_ports DRAM_BA[1]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_BA[1]]
set_property PACKAGE_PIN J19 [get_ports DRAM_BA[0]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_BA[0]]

set_property PACKAGE_PIN J22 [get_ports DRAM_ADDR[12]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_ADDR[12]]
set_property PACKAGE_PIN J15 [get_ports DRAM_ADDR[11]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_ADDR[11]]
set_property PACKAGE_PIN K21 [get_ports DRAM_ADDR[10]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_ADDR[10]]
set_property PACKAGE_PIN H15 [get_ports DRAM_ADDR[9]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_ADDR[9]]
set_property PACKAGE_PIN G18 [get_ports DRAM_ADDR[8]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_ADDR[8]]
set_property PACKAGE_PIN G17 [get_ports DRAM_ADDR[7]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_ADDR[7]]
set_property PACKAGE_PIN H14 [get_ports DRAM_ADDR[6]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_ADDR[6]]
set_property PACKAGE_PIN J14 [get_ports DRAM_ADDR[5]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_ADDR[5]]
set_property PACKAGE_PIN G16 [get_ports DRAM_ADDR[4]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_ADDR[4]]
set_property PACKAGE_PIN J20 [get_ports DRAM_ADDR[3]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_ADDR[3]]
set_property PACKAGE_PIN J21 [get_ports DRAM_ADDR[2]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_ADDR[2]]
set_property PACKAGE_PIN K22 [get_ports DRAM_ADDR[1]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_ADDR[1]]
set_property PACKAGE_PIN H19 [get_ports DRAM_ADDR[0]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_ADDR[0]]

set_property PACKAGE_PIN M13 [get_ports DRAM_DQ[0]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_DQ[0]]
set_property PACKAGE_PIN L13 [get_ports DRAM_DQ[1]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_DQ[1]]
set_property PACKAGE_PIN L16 [get_ports DRAM_DQ[2]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_DQ[2]]
set_property PACKAGE_PIN M15 [get_ports DRAM_DQ[3]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_DQ[3]]
set_property PACKAGE_PIN K16 [get_ports DRAM_DQ[4]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_DQ[4]]
set_property PACKAGE_PIN L14 [get_ports DRAM_DQ[5]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_DQ[5]]
set_property PACKAGE_PIN K17 [get_ports DRAM_DQ[6]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_DQ[6]]
set_property PACKAGE_PIN K14 [get_ports DRAM_DQ[7]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_DQ[7]]
set_property PACKAGE_PIN M21 [get_ports DRAM_DQ[8]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_DQ[8]]
set_property PACKAGE_PIN M22 [get_ports DRAM_DQ[9]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_DQ[9]]
set_property PACKAGE_PIN N19 [get_ports DRAM_DQ[10]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_DQ[10]]
set_property PACKAGE_PIN M20 [get_ports DRAM_DQ[11]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_DQ[11]]
set_property PACKAGE_PIN N18 [get_ports DRAM_DQ[12]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_DQ[12]]
set_property PACKAGE_PIN N20 [get_ports DRAM_DQ[13]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_DQ[13]]
set_property PACKAGE_PIN M16 [get_ports DRAM_DQ[14]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_DQ[14]]
set_property PACKAGE_PIN L15 [get_ports DRAM_DQ[15]]
set_property IOSTANDARD LVCMOS33 [get_ports DRAM_DQ[15]]
